name: cash_discover
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Application version and build number
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: ARS
      fonts:
        - asset: assets/fonts/ARSMaquettePro-Black.ttf
          weight: 800
        - asset: assets/fonts/ARSMaquettePro-BlackItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/ARSMaquettePro-Bold.ttf
          weight: 700
        - asset: assets/fonts/ARSMaquettePro-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/ARSMaquettePro-Italic.ttf
          style: italic
        - asset: assets/fonts/ARSMaquettePro-Light.ttf
          weight: 300
        - asset: assets/fonts/ARSMaquettePro-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/ARSMaquettePro-Medium.ttf
          weight: 500
        - asset: assets/fonts/ARSMaquettePro-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/ARSMaquettePro-Regular.ttf
          weight: 400