// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4MHUlMbCsV4EQXMQAOq4CinETk27W6Yc',
    appId: '1:175567429746:web:428ab535f222a71f25e2eb',
    messagingSenderId: '175567429746',
    projectId: 'cash-discover-hack-week',
    authDomain: 'cash-discover-hack-week.firebaseapp.com',
    storageBucket: 'cash-discover-hack-week.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA57hA24aVmx491isKe3IhZ7Qs41p5anPo',
    appId: '1:175567429746:android:1affcb143fefba7d25e2eb',
    messagingSenderId: '175567429746',
    projectId: 'cash-discover-hack-week',
    storageBucket: 'cash-discover-hack-week.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE3dUdQUo1n0Cp1Be9QbcWubiCLhv-CKc',
    appId: '1:175567429746:ios:ca8c2b2142266d1625e2eb',
    messagingSenderId: '175567429746',
    projectId: 'cash-discover-hack-week',
    storageBucket: 'cash-discover-hack-week.appspot.com',
    iosClientId: '175567429746-pbd7vgd4le6f35h0e1nh7krv1m4en6da.apps.googleusercontent.com',
    iosBundleId: 'com.example.cashDiscover',
  );
}
